"""adding a data into db

Revision ID: 31aa18593d73
Revises: 9153a281a14e
Create Date: 2026-01-20 17:00:25.996023

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.orm import Session

from core.data_helper import add_data_into_db_sync, get_data_sync

# revision identifiers, used by Alembic.
revision: str = "31aa18593d73"
down_revision: Union[str, Sequence[str], None] = "9153a281a14e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    data = get_data_sync()
    bind = op.get_bind()
    session = Session(bind=bind)

    add_data_into_db_sync(data, session)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM tasks")
    op.execute("DELETE FROM users")
    # ### end Alembic commands ###
