"""added user_id to task, and password to User, and relationships

Revision ID: 9153a281a14e
Revises: e546e7373b7e
Create Date: 2026-01-02 13:26:51.660165

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9153a281a14e"
down_revision: Union[str, Sequence[str], None] = "e546e7373b7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("user", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "tasks", "users", ["user"], ["id"])
    op.add_column("users", sa.Column("password", sa.String(length=255), nullable=False))
    op.create_index(op.f("ix_users_password"), "users", ["password"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_password"), table_name="users")
    op.drop_column("users", "password")
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_column("tasks", "user")
    # ### end Alembic commands ###
