"""added user_id to task, and password to User, and relationships

Revision ID: 9153a281a14e
Revises: e546e7373b7e
Create Date: 2026-01-02 13:26:51.660165

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9153a281a14e"
down_revision: Union[str, Sequence[str], None] = "e546e7373b7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("user_id", sa.Integer(), nullable=False, server_default="1")
    )
    op.create_foreign_key("fk_tasks_user", "tasks", "users", ["user_id"], ["id"])
    op.alter_column("tasks", "user_id", server_default=None)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                          WHERE table_name='users' AND column_name='password') THEN
                ALTER TABLE users ADD COLUMN password VARCHAR(255) NOT NULL DEFAULT '';
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_indexes 
                WHERE tablename = 'users' 
                AND indexname = 'ix_users_password'
            ) THEN
                CREATE INDEX ix_users_password ON users (password);
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        constraint_name="fk_tasks_user",
        table_name="tasks",
        type_="foreignkey",
        if_exists=True,
    )
    op.drop_index(op.f("ix_users_password"), table_name="users")
    op.drop_column("users", "password")
    op.drop_column("tasks", "user_id")
    # ### end Alembic commands ###
